MONGODB_HOST: mongodb.dev86aws.fun
REDIS_HOST: redis.dev86aws.fun
CATALOGUE_HOST: catalogue.dev86aws.fun
CART_HOST: cart.dev86aws.fun
USER_HOST: user.dev86aws.fun
RABBITMQ_HOST: rabbitmq.dev86aws.fun
MYSQL_HOST: mysql.dev86aws.fun
SHIPPING_HOST: shipping.dev86aws.fun
PAYMENT_HOST: payment.dev86aws.fun