[mongodb]
mongodb.dev86aws.fun

[redis]
redis.dev86aws.fun

[mysql]
mysql.dev86aws.fun

[rabbitmq]
rabbitmq.dev86aws.fun

[catalogue]
catalogue.dev86aws.fun

[cart]
cart.dev86aws.fun

[user]
user.dev86aws.fun

[shipping]
shipping.dev86aws.fun

[payment]
payment.dev86aws.fun

[frontend]
frontend.dev86aws.fun

[local]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local:vars]
NAME=from inventory
; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar